### PR TITLE
Alphabetical sidebar

### PR DESCRIPTION
**Pull request by LegendaryBob13**
Some items on the sidebar weren't in alphabetical order.

### CODE REVIEW

**Comment by LegendaryBob13** [comment]
I also decided to keep GeyserAddons under GeyserMC due to it being best to read the GeyserMC article before reading GeyserAddons.

**Review by ClumsyAdmin — CHANGES_REQUESTED** [review]
Vault isn't aligned in sidebar.jar

**Comment by LegendaryBob13** [comment]
> Vault isn't aligned in sidebar.jar

I think this might be a github thing... If you go to my repository it is aligned.

**Comment by LegendaryBob13** [comment]
Ah wait its because I used tabs instead of spaces... 1 minute.

**Pull request merged**
